/**
 * Maps GDELT FIPS 10-4 country codes to ISO 3166-1 alpha-2 codes and display names.
 *
 * GDELT uses FIPS 10-4 codes internally. GeoJSON (Natural Earth) uses ISO alpha-3.
 * This module bridges both directions.
 *
 * Sources:
 *   - FIPS 10-4: https://en.wikipedia.org/wiki/FIPS_10-4
 *   - ISO 3166-1: https://en.wikipedia.org/wiki/ISO_3166-1
 */

// FIPS → { iso2, iso3, name }
export const FIPS_TO_ISO = {
  AF: { iso2: 'AF', iso3: 'AFG', name: 'Afghanistan' },
  AG: { iso2: 'DZ', iso3: 'DZA', name: 'Algeria' },
  AJ: { iso2: 'AZ', iso3: 'AZE', name: 'Azerbaijan' },
  AL: { iso2: 'AL', iso3: 'ALB', name: 'Albania' },
  AM: { iso2: 'AM', iso3: 'ARM', name: 'Armenia' },
  AO: { iso2: 'AO', iso3: 'AGO', name: 'Angola' },
  AR: { iso2: 'AR', iso3: 'ARG', name: 'Argentina' },
  AS: { iso2: 'AU', iso3: 'AUS', name: 'Australia' },
  AU: { iso2: 'AT', iso3: 'AUT', name: 'Austria' },
  BA: { iso2: 'BH', iso3: 'BHR', name: 'Bahrain' },
  BC: { iso2: 'BW', iso3: 'BWA', name: 'Botswana' },
  BE: { iso2: 'BE', iso3: 'BEL', name: 'Belgium' },
  BF: { iso2: 'BS', iso3: 'BHS', name: 'Bahamas' },
  BG: { iso2: 'BD', iso3: 'BGD', name: 'Bangladesh' },
  BL: { iso2: 'BO', iso3: 'BOL', name: 'Bolivia' },
  BM: { iso2: 'MM', iso3: 'MMR', name: 'Myanmar' },
  BN: { iso2: 'BJ', iso3: 'BEN', name: 'Benin' },
  BO: { iso2: 'BY', iso3: 'BLR', name: 'Belarus' },
  BP: { iso2: 'SB', iso3: 'SLB', name: 'Solomon Islands' },
  BR: { iso2: 'BR', iso3: 'BRA', name: 'Brazil' },
  BT: { iso2: 'BT', iso3: 'BTN', name: 'Bhutan' },
  BU: { iso2: 'BG', iso3: 'BGR', name: 'Bulgaria' },
  BX: { iso2: 'BN', iso3: 'BRN', name: 'Brunei' },
  BY: { iso2: 'BI', iso3: 'BDI', name: 'Burundi' },
  CA: { iso2: 'CA', iso3: 'CAN', name: 'Canada' },
  CB: { iso2: 'KH', iso3: 'KHM', name: 'Cambodia' },
  CD: { iso2: 'TD', iso3: 'TCD', name: 'Chad' },
  CF: { iso2: 'CG', iso3: 'COG', name: 'Republic of Congo' },
  CG: { iso2: 'CD', iso3: 'COD', name: 'Democratic Republic of Congo' },
  CH: { iso2: 'CN', iso3: 'CHN', name: 'China' },
  CI: { iso2: 'CL', iso3: 'CHL', name: 'Chile' },
  CJ: { iso2: 'KY', iso3: 'CYM', name: 'Cayman Islands' },
  CM: { iso2: 'CM', iso3: 'CMR', name: 'Cameroon' },
  CN: { iso2: 'KM', iso3: 'COM', name: 'Comoros' },
  CO: { iso2: 'CO', iso3: 'COL', name: 'Colombia' },
  CS: { iso2: 'CR', iso3: 'CRI', name: 'Costa Rica' },
  CT: { iso2: 'CF', iso3: 'CAF', name: 'Central African Republic' },
  CU: { iso2: 'CU', iso3: 'CUB', name: 'Cuba' },
  CV: { iso2: 'CV', iso3: 'CPV', name: 'Cape Verde' },
  CY: { iso2: 'CY', iso3: 'CYP', name: 'Cyprus' },
  DA: { iso2: 'DK', iso3: 'DNK', name: 'Denmark' },
  DJ: { iso2: 'DJ', iso3: 'DJI', name: 'Djibouti' },
  DO: { iso2: 'DO', iso3: 'DOM', name: 'Dominican Republic' },
  DR: { iso2: 'DM', iso3: 'DMA', name: 'Dominica' },
  EC: { iso2: 'EC', iso3: 'ECU', name: 'Ecuador' },
  EG: { iso2: 'EG', iso3: 'EGY', name: 'Egypt' },
  EI: { iso2: 'IE', iso3: 'IRL', name: 'Ireland' },
  EK: { iso2: 'GQ', iso3: 'GNQ', name: 'Equatorial Guinea' },
  EN: { iso2: 'EE', iso3: 'EST', name: 'Estonia' },
  ER: { iso2: 'ER', iso3: 'ERI', name: 'Eritrea' },
  ET: { iso2: 'ET', iso3: 'ETH', name: 'Ethiopia' },
  EZ: { iso2: 'CZ', iso3: 'CZE', name: 'Czech Republic' },
  FI: { iso2: 'FI', iso3: 'FIN', name: 'Finland' },
  FJ: { iso2: 'FJ', iso3: 'FJI', name: 'Fiji' },
  FR: { iso2: 'FR', iso3: 'FRA', name: 'France' },
  GA: { iso2: 'GM', iso3: 'GMB', name: 'Gambia' },
  GB: { iso2: 'GA', iso3: 'GAB', name: 'Gabon' },
  GG: { iso2: 'GE', iso3: 'GEO', name: 'Georgia' },
  GH: { iso2: 'GH', iso3: 'GHA', name: 'Ghana' },
  GJ: { iso2: 'GD', iso3: 'GRD', name: 'Grenada' },
  GM: { iso2: 'DE', iso3: 'DEU', name: 'Germany' },
  GQ: { iso2: 'GU', iso3: 'GUM', name: 'Guam' },
  GR: { iso2: 'GR', iso3: 'GRC', name: 'Greece' },
  GT: { iso2: 'GT', iso3: 'GTM', name: 'Guatemala' },
  GV: { iso2: 'GN', iso3: 'GIN', name: 'Guinea' },
  GY: { iso2: 'GY', iso3: 'GUY', name: 'Guyana' },
  HA: { iso2: 'HT', iso3: 'HTI', name: 'Haiti' },
  HO: { iso2: 'HN', iso3: 'HND', name: 'Honduras' },
  HR: { iso2: 'HR', iso3: 'HRV', name: 'Croatia' },
  HU: { iso2: 'HU', iso3: 'HUN', name: 'Hungary' },
  IC: { iso2: 'IS', iso3: 'ISL', name: 'Iceland' },
  ID: { iso2: 'ID', iso3: 'IDN', name: 'Indonesia' },
  IN: { iso2: 'IN', iso3: 'IND', name: 'India' },
  IQ: { iso2: 'IQ', iso3: 'IRQ', name: 'Iraq' },
  IR: { iso2: 'IR', iso3: 'IRN', name: 'Iran' },
  IS: { iso2: 'IL', iso3: 'ISR', name: 'Israel' },
  IT: { iso2: 'IT', iso3: 'ITA', name: 'Italy' },
  IV: { iso2: 'CI', iso3: 'CIV', name: "Côte d'Ivoire" },
  IZ: { iso2: 'IQ', iso3: 'IRQ', name: 'Iraq' },
  JA: { iso2: 'JP', iso3: 'JPN', name: 'Japan' },
  JM: { iso2: 'JM', iso3: 'JAM', name: 'Jamaica' },
  JO: { iso2: 'JO', iso3: 'JOR', name: 'Jordan' },
  KE: { iso2: 'KE', iso3: 'KEN', name: 'Kenya' },
  KG: { iso2: 'KG', iso3: 'KGZ', name: 'Kyrgyzstan' },
  KN: { iso2: 'KP', iso3: 'PRK', name: 'North Korea' },
  KO: { iso2: 'XK', iso3: 'XKX', name: 'Kosovo' },
  KS: { iso2: 'KR', iso3: 'KOR', name: 'South Korea' },
  KT: { iso2: 'KI', iso3: 'KIR', name: 'Kiribati' },
  KU: { iso2: 'KW', iso3: 'KWT', name: 'Kuwait' },
  KZ: { iso2: 'KZ', iso3: 'KAZ', name: 'Kazakhstan' },
  LA: { iso2: 'LA', iso3: 'LAO', name: 'Laos' },
  LE: { iso2: 'LB', iso3: 'LBN', name: 'Lebanon' },
  LG: { iso2: 'LV', iso3: 'LVA', name: 'Latvia' },
  LH: { iso2: 'LT', iso3: 'LTU', name: 'Lithuania' },
  LI: { iso2: 'LR', iso3: 'LBR', name: 'Liberia' },
  LO: { iso2: 'SK', iso3: 'SVK', name: 'Slovakia' },
  LS: { iso2: 'LS', iso3: 'LSO', name: 'Lesotho' },
  LT: { iso2: 'LY', iso3: 'LBY', name: 'Libya' },
  LU: { iso2: 'LU', iso3: 'LUX', name: 'Luxembourg' },
  MA: { iso2: 'MG', iso3: 'MDG', name: 'Madagascar' },
  MB: { iso2: 'MW', iso3: 'MWI', name: 'Malawi' },
  MC: { iso2: 'MO', iso3: 'MAC', name: 'Macau' },
  MD: { iso2: 'MD', iso3: 'MDA', name: 'Moldova' },
  MF: { iso2: 'MV', iso3: 'MDV', name: 'Maldives' },
  MH: { iso2: 'MH', iso3: 'MHL', name: 'Marshall Islands' },
  MI: { iso2: 'MY', iso3: 'MYS', name: 'Malaysia' },
  MK: { iso2: 'MK', iso3: 'MKD', name: 'North Macedonia' },
  ML: { iso2: 'ML', iso3: 'MLI', name: 'Mali' },
  MN: { iso2: 'MC', iso3: 'MCO', name: 'Monaco' },
  MO: { iso2: 'MA', iso3: 'MAR', name: 'Morocco' },
  MP: { iso2: 'MU', iso3: 'MUS', name: 'Mauritius' },
  MR: { iso2: 'MR', iso3: 'MRT', name: 'Mauritania' },
  MT: { iso2: 'MT', iso3: 'MLT', name: 'Malta' },
  MU: { iso2: 'OM', iso3: 'OMN', name: 'Oman' },
  MV: { iso2: 'MV', iso3: 'MDV', name: 'Maldives' },
  MX: { iso2: 'MX', iso3: 'MEX', name: 'Mexico' },
  MY: { iso2: 'MY', iso3: 'MYS', name: 'Malaysia' },
  MZ: { iso2: 'MZ', iso3: 'MOZ', name: 'Mozambique' },
  NA: { iso2: 'NA', iso3: 'NAM', name: 'Namibia' },
  NE: { iso2: 'NI', iso3: 'NIC', name: 'Nicaragua' },
  NG: { iso2: 'NG', iso3: 'NGA', name: 'Nigeria' },
  NH: { iso2: 'VU', iso3: 'VUT', name: 'Vanuatu' },
  NI: { iso2: 'NE', iso3: 'NER', name: 'Niger' },
  NL: { iso2: 'NL', iso3: 'NLD', name: 'Netherlands' },
  NO: { iso2: 'NO', iso3: 'NOR', name: 'Norway' },
  NP: { iso2: 'NP', iso3: 'NPL', name: 'Nepal' },
  NR: { iso2: 'NR', iso3: 'NRU', name: 'Nauru' },
  NS: { iso2: 'SR', iso3: 'SUR', name: 'Suriname' },
  NU: { iso2: 'NI', iso3: 'NIC', name: 'Nicaragua' },
  NZ: { iso2: 'NZ', iso3: 'NZL', name: 'New Zealand' },
  OC: { iso2: 'AU', iso3: 'AUS', name: 'Australia' },
  PA: { iso2: 'PY', iso3: 'PRY', name: 'Paraguay' },
  PC: { iso2: 'FM', iso3: 'FSM', name: 'Micronesia' },
  PE: { iso2: 'PE', iso3: 'PER', name: 'Peru' },
  PH: { iso2: 'PH', iso3: 'PHL', name: 'Philippines' },
  PK: { iso2: 'PK', iso3: 'PAK', name: 'Pakistan' },
  PL: { iso2: 'PL', iso3: 'POL', name: 'Poland' },
  PM: { iso2: 'PA', iso3: 'PAN', name: 'Panama' },
  PO: { iso2: 'PT', iso3: 'PRT', name: 'Portugal' },
  PP: { iso2: 'PG', iso3: 'PNG', name: 'Papua New Guinea' },
  PS: { iso2: 'PW', iso3: 'PLW', name: 'Palau' },
  PU: { iso2: 'GW', iso3: 'GNB', name: 'Guinea-Bissau' },
  QA: { iso2: 'QA', iso3: 'QAT', name: 'Qatar' },
  RI: { iso2: 'ID', iso3: 'IDN', name: 'Indonesia' },
  RM: { iso2: 'MH', iso3: 'MHL', name: 'Marshall Islands' },
  RO: { iso2: 'RO', iso3: 'ROU', name: 'Romania' },
  RP: { iso2: 'PH', iso3: 'PHL', name: 'Philippines' },
  RS: { iso2: 'RU', iso3: 'RUS', name: 'Russia' },
  RW: { iso2: 'RW', iso3: 'RWA', name: 'Rwanda' },
  SA: { iso2: 'SA', iso3: 'SAU', name: 'Saudi Arabia' },
  SB: { iso2: 'ST', iso3: 'STP', name: 'São Tomé and Príncipe' },
  SE: { iso2: 'SC', iso3: 'SYC', name: 'Seychelles' },
  SF: { iso2: 'ZA', iso3: 'ZAF', name: 'South Africa' },
  SG: { iso2: 'SN', iso3: 'SEN', name: 'Senegal' },
  SI: { iso2: 'SI', iso3: 'SVN', name: 'Slovenia' },
  SK: { iso2: 'KN', iso3: 'KNA', name: 'Saint Kitts and Nevis' },
  SL: { iso2: 'SL', iso3: 'SLE', name: 'Sierra Leone' },
  SM: { iso2: 'SO', iso3: 'SOM', name: 'Somalia' },
  SN: { iso2: 'SG', iso3: 'SGP', name: 'Singapore' },
  SO: { iso2: 'SO', iso3: 'SOM', name: 'Somalia' },
  SP: { iso2: 'ES', iso3: 'ESP', name: 'Spain' },
  SR: { iso2: 'SZ', iso3: 'SWZ', name: 'Eswatini' },
  ST: { iso2: 'LC', iso3: 'LCA', name: 'Saint Lucia' },
  SU: { iso2: 'SD', iso3: 'SDN', name: 'Sudan' },
  SV: { iso2: 'SV', iso3: 'SLV', name: 'El Salvador' },
  SW: { iso2: 'SE', iso3: 'SWE', name: 'Sweden' },
  SX: { iso2: 'SX', iso3: 'SXM', name: 'Sint Maarten' },
  SY: { iso2: 'SY', iso3: 'SYR', name: 'Syria' },
  SZ: { iso2: 'CH', iso3: 'CHE', name: 'Switzerland' },
  TD: { iso2: 'TT', iso3: 'TTO', name: 'Trinidad and Tobago' },
  TH: { iso2: 'TH', iso3: 'THA', name: 'Thailand' },
  TI: { iso2: 'TJ', iso3: 'TJK', name: 'Tajikistan' },
  TK: { iso2: 'TC', iso3: 'TCA', name: 'Turks and Caicos Islands' },
  TL: { iso2: 'TL', iso3: 'TLS', name: 'Timor-Leste' },
  TN: { iso2: 'TN', iso3: 'TUN', name: 'Tunisia' },
  TO: { iso2: 'TO', iso3: 'TON', name: 'Tonga' },
  TP: { iso2: 'TL', iso3: 'TLS', name: 'Timor-Leste' },
  TS: { iso2: 'TN', iso3: 'TUN', name: 'Tunisia' },
  TT: { iso2: 'TT', iso3: 'TTO', name: 'Trinidad and Tobago' },
  TU: { iso2: 'TR', iso3: 'TUR', name: 'Turkey' },
  TV: { iso2: 'TV', iso3: 'TUV', name: 'Tuvalu' },
  TW: { iso2: 'TW', iso3: 'TWN', name: 'Taiwan' },
  TX: { iso2: 'TM', iso3: 'TKM', name: 'Turkmenistan' },
  TZ: { iso2: 'TZ', iso3: 'TZA', name: 'Tanzania' },
  UG: { iso2: 'UG', iso3: 'UGA', name: 'Uganda' },
  UK: { iso2: 'GB', iso3: 'GBR', name: 'United Kingdom' },
  UN: { iso2: 'US', iso3: 'USA', name: 'United States' },
  UP: { iso2: 'UA', iso3: 'UKR', name: 'Ukraine' },
  UY: { iso2: 'UY', iso3: 'URY', name: 'Uruguay' },
  UZ: { iso2: 'UZ', iso3: 'UZB', name: 'Uzbekistan' },
  VC: { iso2: 'VC', iso3: 'VCT', name: 'Saint Vincent and the Grenadines' },
  VE: { iso2: 'VE', iso3: 'VEN', name: 'Venezuela' },
  VM: { iso2: 'VN', iso3: 'VNM', name: 'Vietnam' },
  VT: { iso2: 'VA', iso3: 'VAT', name: 'Vatican City' },
  WA: { iso2: 'NA', iso3: 'NAM', name: 'Namibia' },
  WI: { iso2: 'EH', iso3: 'ESH', name: 'Western Sahara' },
  WS: { iso2: 'WS', iso3: 'WSM', name: 'Samoa' },
  WZ: { iso2: 'SZ', iso3: 'SWZ', name: 'Eswatini' },
  YM: { iso2: 'YE', iso3: 'YEM', name: 'Yemen' },
  ZA: { iso2: 'ZM', iso3: 'ZMB', name: 'Zambia' },
  ZI: { iso2: 'ZW', iso3: 'ZWE', name: 'Zimbabwe' },
}

// Build reverse lookup: iso3 → fips
export const ISO3_TO_FIPS = Object.fromEntries(
  Object.entries(FIPS_TO_ISO).map(([fips, val]) => [val.iso3, fips])
)

// Build name lookup: lowercase name → iso3
export const NAME_TO_ISO3 = Object.fromEntries(
  Object.entries(FIPS_TO_ISO).map(([, val]) => [val.name.toLowerCase(), val.iso3])
)

export function fipsToIso3(fipsCode) {
  return FIPS_TO_ISO[fipsCode]?.iso3 ?? null
}

export function iso3ToFips(iso3Code) {
  return ISO3_TO_FIPS[iso3Code] ?? null
}

export function fipsToName(fipsCode) {
  return FIPS_TO_ISO[fipsCode]?.name ?? null
}
